export const MEAL_LIST_REQUEST = 'MEAL_LIST_REQUEST'
export const MEAL_LIST_SUCCESS = 'MEAL_LIST_SUCCESS'
export const MEAL_LIST_FAIL = 'MEAL_LIST_FAIL'

export const MEAL_DETAILS_REQUEST = 'MEAL_DETAILS_REQUEST'
export const MEAL_DETAILS_SUCCESS = 'MEAL_DETAILS_SUCCESS'
export const MEAL_DETAILS_FAIL = 'MEAL_DETAILS_FAIL'

export const MEAL_SEARCH_REQUEST = 'MEAL_SEARCH_REQUEST'
export const MEAL_SEARCH_SUCCESS = 'MEAL_SEARCH_SUCCESS'
export const MEAL_SEARCH_FAIL = 'MEAL_SEARCH_FAIL'

export const MEAL_RANDOM_REQUEST = 'MEAL_RANDOM_REQUEST'
export const MEAL_RANDOM_SUCCESS = 'MEAL_RANDOM_SUCCESS'
export const MEAL_RANDOM_FAIL = 'MEAL_RANDOM_FAIL'



